l=list(range(0,10,2))
print(l)
n=[10,20,30,40]
print(len(n))
print("\n")
n=[1,2,2,2,2,3,3]
print(n.count(1))
print(n.count(2))
print(n.count(3))
print(n.count(4))
print("\n")

print(n.index(1))
print(n.index(2))
print(n.index(3))
print("\n")
list=[]
list.append("A")
list.append("B")
list.append(3)
print(list)
print("\n")
list=[]
for i in range(0,101,10):
    list.append(i)
print(list)
print("\n")
n=[1,2,3,4,5]
n.insert(1,888)
print(n)
print("\n")
order1=["Chicken","Mutton","Fish"]
order2=["RC","KF","FO"]
order1.extend(order2)
print(order1)
print(order2)
print("\n")
n=[10,20,10,30]
n.remove(10)
print(n)
print("\n")
print(n.pop())
print(n)
print("\n")
n.append(300)
n.reverse()
print(n)
print("\n")
n=[20,5,15,10,0]
n.sort()
print(n)
s=["Dog","Banana","Cat","Apple"]
s.sort()
print(s)
print("\n")
y=s.copy()
y[1]=700
print(s)
print(y)